site_name: CSketch

site_url: https://anandology.github.io/csketch/
repo_url: https://github.com/anandology/csketch/

theme:
  name: material
  features:
    - navigation.footer

nav:
  - index.md
  - installing.md
  - api.md
  - examples.md

markdown_extensions:
  - pymdownx.superfences

extra_css:
  - css/csketch.css