site_name: CSketch

site_url: https://anandology.github.io/csketch/
repo_url: https://github.com/anandology/csketch/

theme:
  name: material
  features:
    - navigation.footer
    - content.code.copy

nav:
  - index.md
  - installation.md
  - getting-started.md
  - api.md
  - gallery/index.md

markdown_extensions:
  - pymdownx.superfences

extra_css:
  - css/csketch.css